/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MINMAX_H_RPCGEN
#define _MINMAX_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef struct {
	u_int vect_len;
	int *vect_val;
} vect;

struct minmax_t {
	int min;
	int max;
};
typedef struct minmax_t minmax_t;

#define MINMAX_PROG 1
#define MINMAX_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define minmax 1
extern  minmax_t * minmax_1(vect *, CLIENT *);
extern  minmax_t * minmax_1_svc(vect *, struct svc_req *);
extern int minmax_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define minmax 1
extern  minmax_t * minmax_1();
extern  minmax_t * minmax_1_svc();
extern int minmax_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_vect (XDR *, vect*);
extern  bool_t xdr_minmax_t (XDR *, minmax_t*);

#else /* K&R C */
extern bool_t xdr_vect ();
extern bool_t xdr_minmax_t ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MINMAX_H_RPCGEN */
