/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "minmax.h"

bool_t
xdr_vect (XDR *xdrs, vect *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->vect_val, (u_int *) &objp->vect_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_minmax_t (XDR *xdrs, minmax_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->min))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->max))
		 return FALSE;
	return TRUE;
}
