/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "minmax.h"


void
minmax_prog_1(char *host, vect v)
{
	CLIENT *clnt;
	minmax_t  *result_1;

#ifndef	DEBUG
	clnt = clnt_create (host, MINMAX_PROG, MINMAX_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = minmax_1(&v, clnt);
	if (result_1 == (minmax_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("minmax({ ");
	for (int i = 0; i < v.vect_len; ++i){
		printf("%d ", v.vect_val[i]);
	}
	printf("}) -> min : %d, max : %d\n", result_1->min, result_1->max);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	vect v;

	if (argc < 3) {
		printf ("usage: %s server_host, vector_size\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	
	v.vect_len = atoi(argv[2]);
	v.vect_val = malloc(sizeof(int) * v.vect_len);

	printf("entrez les %d valeurs du vecteur : ", v.vect_len);

	for (int i = 0; i < v.vect_len; ++i){
		scanf("%d", &v.vect_val[i]);
	}

	minmax_prog_1 (host, v);
exit (0);
}
