/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "minmax.h"

minmax_t *
minmax_1_svc(vect *argp, struct svc_req *rqstp)
{
	static minmax_t  result;

	result.min = argp->vect_val[0];
	result.max = argp->vect_val[0];

	for (int i = 1; i < argp->vect_len; ++i) {
		if (result.min > argp->vect_val[i])
			result.min = argp-> vect_val[i];
		if (result.max < argp->vect_val[i])
			result.max = argp-> vect_val[i];
	}

	printf("minmax({ ");
	for (int i = 0; i < argp->vect_len; ++i){
		printf("%d ", argp->vect_val[i]);
	}
	printf("}) -> min : %d, max : %d\n", result.min, result.max);

	return &result;
}
