/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "prime.h"
#include "math.h"

bool_t *
is_prime_1_svc(int *argp, struct svc_req *rqstp)
{
	static bool_t  result = 1;
	int number = *argp;

	for (int i = 2; i < sqrt(number); ++i) {
		if (number % i == 0) {
			printf("%d n'est pas premier\n", number);
			result = 0;
			return &result;
		}
	}

	printf("%d est premier\n", number);	

	return &result;
}
