/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "prime.h"


void
prime_prog_1(char *host, int number)
{
	CLIENT *clnt;
	bool_t  *result_1;
	int  is_prime_1_arg = number;

#ifndef	DEBUG
	clnt = clnt_create (host, PRIME_PROG, PRIME_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = is_prime_1(&is_prime_1_arg, clnt);
	if (result_1 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int number;
	if (argc < 3) {
		printf ("usage: %s server_host number\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	number = atoi(argv[2]);
	prime_prog_1 (host, number);
exit (0);
}
