/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "concours.h"

liste_clients clients = {0, NULL};
int nb_clients = 0;

void client_cpy(client *c1, client *c2) {
	strcpy(c1->nom, c2->nom);
	strcpy(c1->prenom, c2->prenom);
	strcpy(c1->adresse, c2->adresse);
	c1->age = c2->age;
}

void print_liste_clients(liste_clients* clients) {
	for (int i = 0; i < clients->liste_clients_len ; ++i) {
		if(strcmp(clients->liste_clients_val[i].nom, "") != 0)
			printf("%s %s\n", clients->liste_clients_val[i].nom, clients->liste_clients_val[i].prenom);
	}
}

bool_t *
ajouter_client_1_svc(client *argp, struct svc_req *rqstp)
{
	static bool_t result = 1;
	int can_add_client = 0;

	for (int i = 0; i < clients.liste_clients_len; ++i) {
		if(strcmp(clients.liste_clients_val[i].nom, "") == 0) {
			client_cpy(&clients.liste_clients_val[i], argp); 
			can_add_client = 1;
			break;
		}
	}

	if (!can_add_client){

		printf("allocation d'une liste plus grande\n");
		
		liste_clients temp = {clients.liste_clients_len, clients.liste_clients_val};

		clients.liste_clients_len++;
		clients.liste_clients_val = malloc(sizeof(client) * clients.liste_clients_len);
		
		for (int i = 0; i < clients.liste_clients_len - 1; ++i) {
			client_cpy(&clients.liste_clients_val[i], &temp.liste_clients_val[i]);
		}
		client_cpy(&clients.liste_clients_val[clients.liste_clients_len - 1], argp);
	}

	printf("liste de clients :\n");

	print_liste_clients(&clients);

	nb_clients++;

	return &result;
}

liste_clients *
lister_clients_1_svc(void *argp, struct svc_req *rqstp)
{
	printf("liste de clients :\n");

	print_liste_clients(&clients);

	return &clients;
}

bool_t *
supprimer_client_1_svc(char **argp, struct svc_req *rqstp)
{
	static bool_t result = 0;

	for (int i = 0; i < clients.liste_clients_len; ++i) {
		if(strcmp(clients.liste_clients_val[i].nom, *argp) == 0) {
			strcpy(clients.liste_clients_val[i].nom, ""); 
			strcpy(clients.liste_clients_val[i].prenom, ""); 
			strcpy(clients.liste_clients_val[i].adresse, ""); 
			clients.liste_clients_val[i].age = 0;
			result = 1;
			break;
		}
	}

	if(result)
		nb_clients--;

	return &result;
}

int *
compter_clients_1_svc(client *argp, struct svc_req *rqstp)
{
	return &nb_clients;
}
