/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CONCOURS_H_RPCGEN
#define _CONCOURS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define STR_MAX_LEN 512

struct client {
	char nom[STR_MAX_LEN];
	char prenom[STR_MAX_LEN];
	char adresse[STR_MAX_LEN];
	float age;
};
typedef struct client client;

typedef struct {
	u_int liste_clients_len;
	client *liste_clients_val;
} liste_clients;

enum ACTION_CLIENT {
	AJOUTER = 0,
	LISTER = 1,
	SUPPRIMER = 2,
	COMPTER = 3,
};
typedef enum ACTION_CLIENT ACTION_CLIENT;

#define CONCOURS_PROG 1
#define CONCOURS_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ajouter_client 1
extern  bool_t * ajouter_client_1(client *, CLIENT *);
extern  bool_t * ajouter_client_1_svc(client *, struct svc_req *);
#define lister_clients 2
extern  liste_clients * lister_clients_1(void *, CLIENT *);
extern  liste_clients * lister_clients_1_svc(void *, struct svc_req *);
#define supprimer_client 3
extern  bool_t * supprimer_client_1(char **, CLIENT *);
extern  bool_t * supprimer_client_1_svc(char **, struct svc_req *);
#define compter_clients 4
extern  int * compter_clients_1(client *, CLIENT *);
extern  int * compter_clients_1_svc(client *, struct svc_req *);
extern int concours_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ajouter_client 1
extern  bool_t * ajouter_client_1();
extern  bool_t * ajouter_client_1_svc();
#define lister_clients 2
extern  liste_clients * lister_clients_1();
extern  liste_clients * lister_clients_1_svc();
#define supprimer_client 3
extern  bool_t * supprimer_client_1();
extern  bool_t * supprimer_client_1_svc();
#define compter_clients 4
extern  int * compter_clients_1();
extern  int * compter_clients_1_svc();
extern int concours_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_client (XDR *, client*);
extern  bool_t xdr_liste_clients (XDR *, liste_clients*);
extern  bool_t xdr_ACTION_CLIENT (XDR *, ACTION_CLIENT*);

#else /* K&R C */
extern bool_t xdr_client ();
extern bool_t xdr_liste_clients ();
extern bool_t xdr_ACTION_CLIENT ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CONCOURS_H_RPCGEN */
