/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "concours.h"


void
concours_prog_1(char *host, ACTION_CLIENT action)
{
	CLIENT *clnt;
	bool_t  *result_1;
	client  ajouter_client_1_arg;
	liste_clients  *result_2;
	char *lister_clients_1_arg;
	bool_t  *result_3;
	char*  supprimer_client_1_arg = malloc(sizeof(char) * STR_MAX_LEN);
	strcpy(supprimer_client_1_arg, "");
	int  *result_4;
	client  compter_clients_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CONCOURS_PROG, CONCOURS_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	switch (action) {

		case AJOUTER :
			printf("Nom : "); scanf("%s", ajouter_client_1_arg.nom);
			printf("Prenom : "); scanf("%s", ajouter_client_1_arg.prenom);
			printf("Adresse : "); scanf("%s", ajouter_client_1_arg.adresse);
			printf("Age : "); scanf("%f", &ajouter_client_1_arg.age);
			result_1 = ajouter_client_1(&ajouter_client_1_arg, clnt);
			if (result_1 == (bool_t *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			if (*result_1)
				printf("Ajout reussi\n");
			else
				printf("Ajout echouée\n");
		break;
		case LISTER : 
			result_2 = lister_clients_1((void*)&lister_clients_1_arg, clnt);
			if (result_2 == (liste_clients *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			printf("liste de clients :\n");
			for (int i = 0; i < result_2->liste_clients_len ; ++i) {
				printf("%s %s\n", result_2->liste_clients_val[i].nom, result_2->liste_clients_val[i].prenom);
			}
		break;
		case SUPPRIMER : 
			printf("Nom : "); scanf("%s", supprimer_client_1_arg);
			result_3 = supprimer_client_1(&supprimer_client_1_arg, clnt);
			if (result_3 == (bool_t *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			if (*result_3)
				printf("Suppression reussie\n");
			else
				printf("Suppression echouée\n");
		break;
		case COMPTER : 
			result_4 = compter_clients_1(&compter_clients_1_arg, clnt);
			if (result_4 == (int *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			printf("nombre de clients : %d\n", *result_4);
		break;
		default : 
			printf("Erreur : action impossible\n");
		break;
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	ACTION_CLIENT action;
	if (argc < 3) {
		printf ("usage: %s server_host action (AJOUTER = 0, LISTER = 1, SUPPRIMER = 2, COMPTER = 3\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	action = atoi(argv[2]);
	concours_prog_1 (host, action);
exit (0);
}


/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */